// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: wiserroommini

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void LOGOENTRA_Animation( lv_obj_t *TargetObject, int delay);

// SCREEN: ui_INPUTS
void ui_INPUTS_screen_init(void);
lv_obj_t *ui_INPUTS;
void ui_event_LIVRECHECK( lv_event_t * e);
lv_obj_t *ui_LIVRECHECK;
void ui_event_OCUPADOCHECK( lv_event_t * e);
lv_obj_t *ui_OCUPADOCHECK;
void ui_event_CHECKINCHECK( lv_event_t * e);
lv_obj_t *ui_CHECKINCHECK;

// SCREEN: ui_LogoPage
void ui_LogoPage_screen_init(void);
void ui_event_LogoPage( lv_event_t * e);
lv_obj_t *ui_LogoPage;
lv_obj_t *ui_LogoWiser;

// SCREEN: ui_MainPage
void ui_MainPage_screen_init(void);
lv_obj_t *ui_MainPage;
lv_obj_t *ui_PanelLivreVerde;
void ui_event_StatusSalaLivre( lv_event_t * e);
lv_obj_t *ui_StatusSalaLivre;
lv_obj_t *ui_PanelOcupadoVermelho;
void ui_event_StatusSalaOcupada( lv_event_t * e);
lv_obj_t *ui_StatusSalaOcupada;
lv_obj_t *ui_PanelCheckinAmarelo;
void ui_event_StatusSalaReservada( lv_event_t * e);
lv_obj_t *ui_StatusSalaReservada;
void ui_event_NomeSala( lv_event_t * e);
lv_obj_t *ui_NomeSala;
lv_obj_t *ui_TituloeHostdaReuniao;
lv_obj_t *ui_NomeHost;
lv_obj_t *ui_HorariodaProximaReuniao;
lv_obj_t *ui_HorarioLimiteCheckin;
lv_obj_t *ui_linhasuperior;
lv_obj_t *ui_linhainferior;
lv_obj_t *ui_blurPanel;
void ui_event_EstenderDropdown( lv_event_t * e);
lv_obj_t *ui_EstenderDropdown;
void ui_event_LiberarDropdown( lv_event_t * e);
lv_obj_t *ui_LiberarDropdown;
void ui_event_ReservarDropdown( lv_event_t * e);
lv_obj_t *ui_ReservarDropdown;
void ui_event_RealizarCheckinDropDown( lv_event_t * e);
lv_obj_t *ui_RealizarCheckinDropDown;
lv_obj_t *ui_SpinnerPadrao;
lv_obj_t *ui_SPINNERTITLE;

// SCREEN: ui_SetupPage
void ui_SetupPage_screen_init(void);
lv_obj_t *ui_SetupPage;
void ui_event_Roller1( lv_event_t * e);
lv_obj_t *ui_Roller1;
lv_obj_t *ui_Label2;
void ui_event_BOTAOCONFIRMARNOVASALA( lv_event_t * e);
lv_obj_t *ui_BOTAOCONFIRMARNOVASALA;
lv_obj_t *ui_Label3;
void ui_event_BOTAOSAIRDAESCOLHADESALA( lv_event_t * e);
lv_obj_t *ui_BOTAOSAIRDAESCOLHADESALA;
lv_obj_t *ui_Label1;
void ui_event____initial_actions0( lv_event_t * e);
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_1872679383[1] = {&ui_img_1535922526};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void LOGOENTRA_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 3000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_0, 0, 255 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_in);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_opacity );
lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_LIVRECHECK( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_flag_modify( ui_PanelLivreVerde, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_screen_change( ui_MainPage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
      _ui_flag_modify( ui_ReservarDropdown, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_EstenderDropdown, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_LiberarDropdown, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_PanelOcupadoVermelho, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_PanelCheckinAmarelo, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_HorariodaProximaReuniao, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_TituloeHostdaReuniao, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_RealizarCheckinDropDown, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_HorarioLimiteCheckin, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_OCUPADOCHECK( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_screen_change( ui_MainPage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
      _ui_flag_modify( ui_PanelOcupadoVermelho, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_EstenderDropdown, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_LiberarDropdown, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_PanelCheckinAmarelo, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_PanelLivreVerde, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_ReservarDropdown, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_HorariodaProximaReuniao, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_TituloeHostdaReuniao, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_RealizarCheckinDropDown, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_HorarioLimiteCheckin, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_CHECKINCHECK( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_screen_change( ui_MainPage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
      _ui_flag_modify( ui_PanelCheckinAmarelo, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_EstenderDropdown, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_ReservarDropdown, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_LiberarDropdown, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_PanelLivreVerde, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_PanelOcupadoVermelho, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_HorariodaProximaReuniao, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_TituloeHostdaReuniao, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_HorariodaProximaReuniao, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_RealizarCheckinDropDown, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_HorarioLimiteCheckin, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}
void ui_event_LogoPage( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      LOGOENTRA_Animation(ui_LogoPage, 1000);
}
if ( event_code == LV_EVENT_SCREEN_LOADED) {
      _ui_screen_change( ui_INPUTS, LV_SCR_LOAD_ANIM_FADE_ON, 300, 5000);
}
}
void ui_event_StatusSalaLivre( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( ui_INPUTS, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
}
}
void ui_event_StatusSalaOcupada( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( ui_INPUTS, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
}
}
void ui_event_StatusSalaReservada( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( ui_INPUTS, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
}
}
void ui_event_NomeSala( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_LONG_PRESSED) {
      _ui_screen_change( ui_SetupPage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 2);
}
}
void ui_event_EstenderDropdown( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_blurPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_flag_modify( ui_blurPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_blurPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      estender_func( e );
      _ui_screen_change( ui_INPUTS, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
      _ui_label_set_property(ui_SPINNERTITLE, _UI_LABEL_PROPERTY_TEXT, "ESTENDENDO A REUNIAO");
}
}
void ui_event_LiberarDropdown( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_blurPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_flag_modify( ui_blurPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_blurPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      liberarsala_func( e );
      _ui_screen_change( ui_INPUTS, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
      _ui_label_set_property(ui_SPINNERTITLE, _UI_LABEL_PROPERTY_TEXT, "LIBERANDO A SALA");
}
}
void ui_event_ReservarDropdown( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_blurPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_flag_modify( ui_blurPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_blurPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      reservaimediata_func( e );
      _ui_screen_change( ui_INPUTS, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
      _ui_label_set_property(ui_SPINNERTITLE, _UI_LABEL_PROPERTY_TEXT, "REALIZANDO A RESERVA");
}
}
void ui_event_RealizarCheckinDropDown( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_blurPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_flag_modify( ui_blurPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_blurPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      realizarcheckin_func( e );
      _ui_screen_change( ui_INPUTS, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
      _ui_label_set_property(ui_SPINNERTITLE, _UI_LABEL_PROPERTY_TEXT, "REALIZANDO O CHECK-IN");
}
}
void ui_event_Roller1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_label_set_property(ui_NomeSala, _UI_LABEL_PROPERTY_TEXT, "@VALUE_CHANGED");
      _ui_flag_modify( ui_BOTAOCONFIRMARNOVASALA, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}
void ui_event_BOTAOCONFIRMARNOVASALA( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( ui_INPUTS, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
      FAZERATROCADESALA( e );
}
}
void ui_event_BOTAOSAIRDAESCOLHADESALA( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( ui_MainPage, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0);
}
}
void ui_event____initial_actions0( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      ATUALIZACALENDAR( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_INPUTS_screen_init();
ui_LogoPage_screen_init();
ui_MainPage_screen_init();
ui_SetupPage_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_obj_add_event_cb(ui____initial_actions0, ui_event____initial_actions0, LV_EVENT_ALL, NULL);

lv_disp_load_scr(ui____initial_actions0);
lv_disp_load_scr( ui_INPUTS);
}
