// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: wiserroommini

#ifndef _WISERROOMMINI_UI_H
#define _WISERROOMMINI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
void LOGOENTRA_Animation( lv_obj_t *TargetObject, int delay);
// SCREEN: ui_INPUTS
void ui_INPUTS_screen_init(void);
extern lv_obj_t *ui_INPUTS;
void ui_event_LIVRECHECK( lv_event_t * e);
extern lv_obj_t *ui_LIVRECHECK;
void ui_event_OCUPADOCHECK( lv_event_t * e);
extern lv_obj_t *ui_OCUPADOCHECK;
void ui_event_CHECKINCHECK( lv_event_t * e);
extern lv_obj_t *ui_CHECKINCHECK;
// SCREEN: ui_LogoPage
void ui_LogoPage_screen_init(void);
void ui_event_LogoPage( lv_event_t * e);
extern lv_obj_t *ui_LogoPage;
extern lv_obj_t *ui_LogoWiser;
// SCREEN: ui_MainPage
void ui_MainPage_screen_init(void);
extern lv_obj_t *ui_MainPage;
extern lv_obj_t *ui_PanelLivreVerde;
void ui_event_StatusSalaLivre( lv_event_t * e);
extern lv_obj_t *ui_StatusSalaLivre;
extern lv_obj_t *ui_PanelOcupadoVermelho;
void ui_event_StatusSalaOcupada( lv_event_t * e);
extern lv_obj_t *ui_StatusSalaOcupada;
extern lv_obj_t *ui_PanelCheckinAmarelo;
void ui_event_StatusSalaReservada( lv_event_t * e);
extern lv_obj_t *ui_StatusSalaReservada;
void ui_event_NomeSala( lv_event_t * e);
extern lv_obj_t *ui_NomeSala;
extern lv_obj_t *ui_TituloeHostdaReuniao;
extern lv_obj_t *ui_NomeHost;
extern lv_obj_t *ui_HorariodaProximaReuniao;
extern lv_obj_t *ui_HorarioLimiteCheckin;
extern lv_obj_t *ui_linhasuperior;
extern lv_obj_t *ui_linhainferior;
extern lv_obj_t *ui_blurPanel;
void ui_event_EstenderDropdown( lv_event_t * e);
extern lv_obj_t *ui_EstenderDropdown;
void ui_event_LiberarDropdown( lv_event_t * e);
extern lv_obj_t *ui_LiberarDropdown;
void ui_event_ReservarDropdown( lv_event_t * e);
extern lv_obj_t *ui_ReservarDropdown;
void ui_event_RealizarCheckinDropDown( lv_event_t * e);
extern lv_obj_t *ui_RealizarCheckinDropDown;
extern lv_obj_t *ui_SpinnerPadrao;
extern lv_obj_t *ui_SPINNERTITLE;
// SCREEN: ui_SetupPage
void ui_SetupPage_screen_init(void);
extern lv_obj_t *ui_SetupPage;
void ui_event_Roller1( lv_event_t * e);
extern lv_obj_t *ui_Roller1;
extern lv_obj_t *ui_Label2;
void ui_event_BOTAOCONFIRMARNOVASALA( lv_event_t * e);
extern lv_obj_t *ui_BOTAOCONFIRMARNOVASALA;
extern lv_obj_t *ui_Label3;
void ui_event_BOTAOSAIRDAESCOLHADESALA( lv_event_t * e);
extern lv_obj_t *ui_BOTAOSAIRDAESCOLHADESALA;
extern lv_obj_t *ui_Label1;
void ui_event____initial_actions0( lv_event_t * e);
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_1535922526);   // assets/Logo-Institucional-Branco-2.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
