// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: wiserroommini

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ATUALIZACALENDAR(lv_event_t * e);
void estender_func(lv_event_t * e);
void liberarsala_func(lv_event_t * e);
void reservaimediata_func(lv_event_t * e);
void realizarcheckin_func(lv_event_t * e);
void FAZERATROCADESALA(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
