// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: wiserroommini

#include "ui.h"

void ATUALIZACALENDAR(lv_event_t * e)
{
	// Your code here
}

void estender_func(lv_event_t * e)
{
	// Your code here
}

void liberarsala_func(lv_event_t * e)
{
	// Your code here
}

void reservaimediata_func(lv_event_t * e)
{
	// Your code here
}

void realizarcheckin_func(lv_event_t * e)
{
	// Your code here
}

void FAZERATROCADESALA(lv_event_t * e)
{
	// Your code here
}
