// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: wiserroommini

#include "ui.h"

void ui_INPUTS_screen_init(void)
{
ui_INPUTS = lv_obj_create(NULL);
lv_obj_clear_flag( ui_INPUTS, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LIVRECHECK = lv_checkbox_create(ui_INPUTS);
lv_checkbox_set_text(ui_LIVRECHECK,"LIVRE");
lv_obj_set_width( ui_LIVRECHECK, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LIVRECHECK, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LIVRECHECK, -148 );
lv_obj_set_y( ui_LIVRECHECK, -64 );
lv_obj_set_align( ui_LIVRECHECK, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_LIVRECHECK, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_OCUPADOCHECK = lv_checkbox_create(ui_INPUTS);
lv_checkbox_set_text(ui_OCUPADOCHECK,"OCUPADO");
lv_obj_set_width( ui_OCUPADOCHECK, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_OCUPADOCHECK, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_OCUPADOCHECK, -127 );
lv_obj_set_y( ui_OCUPADOCHECK, 0 );
lv_obj_set_align( ui_OCUPADOCHECK, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_OCUPADOCHECK, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_CHECKINCHECK = lv_checkbox_create(ui_INPUTS);
lv_checkbox_set_text(ui_CHECKINCHECK,"CHECK-IN");
lv_obj_set_width( ui_CHECKINCHECK, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CHECKINCHECK, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CHECKINCHECK, -131 );
lv_obj_set_y( ui_CHECKINCHECK, -32 );
lv_obj_set_align( ui_CHECKINCHECK, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_CHECKINCHECK, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

lv_obj_add_event_cb(ui_LIVRECHECK, ui_event_LIVRECHECK, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_OCUPADOCHECK, ui_event_OCUPADOCHECK, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_CHECKINCHECK, ui_event_CHECKINCHECK, LV_EVENT_ALL, NULL);

}
