// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: wiserroommini

#include "ui.h"

void ui_LogoPage_screen_init(void)
{
ui_LogoPage = lv_obj_create(NULL);
lv_obj_clear_flag( ui_LogoPage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LogoWiser = lv_img_create(ui_LogoPage);
lv_img_set_src(ui_LogoWiser, &ui_img_1535922526);
lv_obj_set_width( ui_LogoWiser, LV_SIZE_CONTENT);  /// 350
lv_obj_set_height( ui_LogoWiser, LV_SIZE_CONTENT);   /// 161
lv_obj_set_align( ui_LogoWiser, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_LogoWiser, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_LogoWiser, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_LogoPage, ui_event_LogoPage, LV_EVENT_ALL, NULL);

}
