// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: wiserroommini

#include "ui.h"

void ui_MainPage_screen_init(void)
{
ui_MainPage = lv_obj_create(NULL);
lv_obj_clear_flag( ui_MainPage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PanelLivreVerde = lv_obj_create(ui_MainPage);
lv_obj_set_width( ui_PanelLivreVerde, lv_pct(100));
lv_obj_set_height( ui_PanelLivreVerde, lv_pct(100));
lv_obj_set_align( ui_PanelLivreVerde, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelLivreVerde, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PanelLivreVerde, lv_color_hex(0x69FC03), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelLivreVerde, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_PanelLivreVerde, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_StatusSalaLivre = lv_label_create(ui_PanelLivreVerde);
lv_obj_set_width( ui_StatusSalaLivre, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_StatusSalaLivre, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_StatusSalaLivre, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_StatusSalaLivre,"LIVRE");
lv_obj_add_flag( ui_StatusSalaLivre, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_clear_flag( ui_StatusSalaLivre, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_font(ui_StatusSalaLivre, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelOcupadoVermelho = lv_obj_create(ui_MainPage);
lv_obj_set_width( ui_PanelOcupadoVermelho, lv_pct(100));
lv_obj_set_height( ui_PanelOcupadoVermelho, lv_pct(100));
lv_obj_set_align( ui_PanelOcupadoVermelho, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelOcupadoVermelho, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PanelOcupadoVermelho, lv_color_hex(0xFC0303), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelOcupadoVermelho, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_PanelOcupadoVermelho, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_StatusSalaOcupada = lv_label_create(ui_PanelOcupadoVermelho);
lv_obj_set_width( ui_StatusSalaOcupada, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_StatusSalaOcupada, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_StatusSalaOcupada, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_StatusSalaOcupada,"OCUPADA");
lv_obj_add_flag( ui_StatusSalaOcupada, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_clear_flag( ui_StatusSalaOcupada, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_font(ui_StatusSalaOcupada, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelCheckinAmarelo = lv_obj_create(ui_MainPage);
lv_obj_set_width( ui_PanelCheckinAmarelo, lv_pct(100));
lv_obj_set_height( ui_PanelCheckinAmarelo, lv_pct(100));
lv_obj_set_align( ui_PanelCheckinAmarelo, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelCheckinAmarelo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PanelCheckinAmarelo, lv_color_hex(0xFCC803), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelCheckinAmarelo, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_PanelCheckinAmarelo, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_StatusSalaReservada = lv_label_create(ui_PanelCheckinAmarelo);
lv_obj_set_width( ui_StatusSalaReservada, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_StatusSalaReservada, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_StatusSalaReservada, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_StatusSalaReservada,"RESERVADA");
lv_obj_add_flag( ui_StatusSalaReservada, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_clear_flag( ui_StatusSalaReservada, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_font(ui_StatusSalaReservada, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_NomeSala = lv_label_create(ui_MainPage);
lv_obj_set_width( ui_NomeSala, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_NomeSala, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_NomeSala, 0 );
lv_obj_set_y( ui_NomeSala, -2 );
lv_obj_set_align( ui_NomeSala, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_NomeSala,"RIO DE JANEIRO");
lv_obj_add_flag( ui_NomeSala, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_clear_flag( ui_NomeSala, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_NomeSala, lv_color_hex(0xDFD0D0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_NomeSala, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_NomeSala, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TituloeHostdaReuniao = lv_label_create(ui_MainPage);
lv_obj_set_width( ui_TituloeHostdaReuniao, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TituloeHostdaReuniao, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TituloeHostdaReuniao, 0 );
lv_obj_set_y( ui_TituloeHostdaReuniao, -20 );
lv_obj_set_align( ui_TituloeHostdaReuniao, LV_ALIGN_CENTER );
lv_label_set_text(ui_TituloeHostdaReuniao,"Gestao de Espacos RH e DP e TI");
lv_obj_clear_flag( ui_TituloeHostdaReuniao, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_font(ui_TituloeHostdaReuniao, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_NomeHost = lv_label_create(ui_TituloeHostdaReuniao);
lv_obj_set_width( ui_NomeHost, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_NomeHost, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_NomeHost, 0 );
lv_obj_set_y( ui_NomeHost, 30 );
lv_obj_set_align( ui_NomeHost, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_NomeHost,"Guilherme Del Nero");
lv_obj_clear_flag( ui_NomeHost, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_NomeHost, lv_color_hex(0xE9DEDE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_NomeHost, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_NomeHost, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HorariodaProximaReuniao = lv_label_create(ui_MainPage);
lv_obj_set_width( ui_HorariodaProximaReuniao, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HorariodaProximaReuniao, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HorariodaProximaReuniao, 0 );
lv_obj_set_y( ui_HorariodaProximaReuniao, -39 );
lv_obj_set_align( ui_HorariodaProximaReuniao, LV_ALIGN_CENTER );
lv_label_set_text(ui_HorariodaProximaReuniao,"Proxima Reuniao 16h30");
lv_obj_clear_flag( ui_HorariodaProximaReuniao, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_font(ui_HorariodaProximaReuniao, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HorarioLimiteCheckin = lv_label_create(ui_MainPage);
lv_obj_set_width( ui_HorarioLimiteCheckin, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HorarioLimiteCheckin, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HorarioLimiteCheckin, -84 );
lv_obj_set_y( ui_HorarioLimiteCheckin, 223 );
lv_obj_set_align( ui_HorarioLimiteCheckin, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_HorarioLimiteCheckin,"Horario Limite: 15h15");
lv_obj_clear_flag( ui_HorarioLimiteCheckin, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_HorarioLimiteCheckin, lv_color_hex(0xE9DEDE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_HorarioLimiteCheckin, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_HorarioLimiteCheckin, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_linhasuperior = lv_obj_create(ui_MainPage);
lv_obj_set_width( ui_linhasuperior, 386);
lv_obj_set_height( ui_linhasuperior, 3);
lv_obj_set_x( ui_linhasuperior, 0 );
lv_obj_set_y( ui_linhasuperior, -79 );
lv_obj_set_align( ui_linhasuperior, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_linhasuperior, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_linhainferior = lv_obj_create(ui_MainPage);
lv_obj_set_width( ui_linhainferior, 386);
lv_obj_set_height( ui_linhainferior, 3);
lv_obj_set_x( ui_linhainferior, 0 );
lv_obj_set_y( ui_linhainferior, 110 );
lv_obj_set_align( ui_linhainferior, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_linhainferior, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_blurPanel = lv_obj_create(ui_MainPage);
lv_obj_set_width( ui_blurPanel, lv_pct(100));
lv_obj_set_height( ui_blurPanel, lv_pct(100));
lv_obj_set_align( ui_blurPanel, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_blurPanel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_blurPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_blurPanel, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_blurPanel, 200, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_EstenderDropdown = lv_dropdown_create(ui_MainPage);
lv_dropdown_set_options( ui_EstenderDropdown, "15 min\n30 min\n45 min\n60 min\nvoltar" );
lv_dropdown_set_selected_highlight( ui_EstenderDropdown, false);
lv_dropdown_set_text( ui_EstenderDropdown, "ESTENDER");
lv_obj_set_width( ui_EstenderDropdown, 140);
lv_obj_set_height( ui_EstenderDropdown, 50);
lv_obj_set_x( ui_EstenderDropdown, -119 );
lv_obj_set_y( ui_EstenderDropdown, 75 );
lv_obj_set_align( ui_EstenderDropdown, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_EstenderDropdown, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_EstenderDropdown, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_align(ui_EstenderDropdown, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_EstenderDropdown, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_EstenderDropdown, 12, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_EstenderDropdown, lv_color_hex(0x292831), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_EstenderDropdown, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_text_letter_space(lv_dropdown_get_list(ui_EstenderDropdown), 0,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(lv_dropdown_get_list(ui_EstenderDropdown), 10,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(lv_dropdown_get_list(ui_EstenderDropdown), LV_TEXT_ALIGN_LEFT,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(lv_dropdown_get_list(ui_EstenderDropdown), &lv_font_montserrat_20,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(lv_dropdown_get_list(ui_EstenderDropdown), lv_color_hex(0xFFFFFF),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(lv_dropdown_get_list(ui_EstenderDropdown), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_EstenderDropdown), lv_color_hex(0x0D80FF),  LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_EstenderDropdown), 255,  LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_LiberarDropdown = lv_dropdown_create(ui_MainPage);
lv_dropdown_set_options( ui_LiberarDropdown, "Confirmar\nvoltar" );
lv_dropdown_set_selected_highlight( ui_LiberarDropdown, false);
lv_dropdown_set_text( ui_LiberarDropdown, "  LIBERAR");
lv_obj_set_width( ui_LiberarDropdown, 140);
lv_obj_set_height( ui_LiberarDropdown, 50);
lv_obj_set_x( ui_LiberarDropdown, 120 );
lv_obj_set_y( ui_LiberarDropdown, 75 );
lv_obj_set_align( ui_LiberarDropdown, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_LiberarDropdown, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_LiberarDropdown, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_align(ui_LiberarDropdown, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LiberarDropdown, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_LiberarDropdown, 12, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_LiberarDropdown, lv_color_hex(0x292831), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LiberarDropdown, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(lv_dropdown_get_list(ui_LiberarDropdown), &lv_font_montserrat_20,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(lv_dropdown_get_list(ui_LiberarDropdown), lv_color_hex(0xFFFFFF),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(lv_dropdown_get_list(ui_LiberarDropdown), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_LiberarDropdown), lv_color_hex(0x0D80FF),  LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_LiberarDropdown), 255,  LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_ReservarDropdown = lv_dropdown_create(ui_MainPage);
lv_dropdown_set_options( ui_ReservarDropdown, "15 min\n30 min\n45 min\n60 min\nvoltar" );
lv_dropdown_set_selected_highlight( ui_ReservarDropdown, false);
lv_dropdown_set_text( ui_ReservarDropdown, "RESERVAR AGORA");
lv_obj_set_width( ui_ReservarDropdown, 218);
lv_obj_set_height( ui_ReservarDropdown, 50);
lv_obj_set_x( ui_ReservarDropdown, 0 );
lv_obj_set_y( ui_ReservarDropdown, 75 );
lv_obj_set_align( ui_ReservarDropdown, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ReservarDropdown, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_ReservarDropdown, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_align(ui_ReservarDropdown, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ReservarDropdown, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_ReservarDropdown, 12, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_ReservarDropdown, lv_color_hex(0x292831), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ReservarDropdown, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_text_letter_space(lv_dropdown_get_list(ui_ReservarDropdown), 0,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(lv_dropdown_get_list(ui_ReservarDropdown), 10,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(lv_dropdown_get_list(ui_ReservarDropdown), LV_TEXT_ALIGN_LEFT,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(lv_dropdown_get_list(ui_ReservarDropdown), &lv_font_montserrat_20,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(lv_dropdown_get_list(ui_ReservarDropdown), lv_color_hex(0xFFFFFF),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(lv_dropdown_get_list(ui_ReservarDropdown), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_ReservarDropdown), lv_color_hex(0x0D80FF),  LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_ReservarDropdown), 255,  LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_RealizarCheckinDropDown = lv_dropdown_create(ui_MainPage);
lv_dropdown_set_options( ui_RealizarCheckinDropDown, "Confirmar\nvoltar" );
lv_dropdown_set_selected_highlight( ui_RealizarCheckinDropDown, false);
lv_dropdown_set_text( ui_RealizarCheckinDropDown, " CHECK-IN");
lv_obj_set_width( ui_RealizarCheckinDropDown, 140);
lv_obj_set_height( ui_RealizarCheckinDropDown, 50);
lv_obj_set_x( ui_RealizarCheckinDropDown, 120 );
lv_obj_set_y( ui_RealizarCheckinDropDown, 75 );
lv_obj_set_align( ui_RealizarCheckinDropDown, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_RealizarCheckinDropDown, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_RealizarCheckinDropDown, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_align(ui_RealizarCheckinDropDown, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_RealizarCheckinDropDown, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_RealizarCheckinDropDown, 12, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_RealizarCheckinDropDown, lv_color_hex(0x292831), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_RealizarCheckinDropDown, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(lv_dropdown_get_list(ui_RealizarCheckinDropDown), &lv_font_montserrat_20,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(lv_dropdown_get_list(ui_RealizarCheckinDropDown), lv_color_hex(0xFFFFFF),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(lv_dropdown_get_list(ui_RealizarCheckinDropDown), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_RealizarCheckinDropDown), lv_color_hex(0x0D80FF),  LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_RealizarCheckinDropDown), 255,  LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_SpinnerPadrao = lv_spinner_create(ui_MainPage,1000,90);
lv_obj_set_width( ui_SpinnerPadrao, 160);
lv_obj_set_height( ui_SpinnerPadrao, 150);
lv_obj_set_align( ui_SpinnerPadrao, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SpinnerPadrao, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_SpinnerPadrao, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_pad_left(ui_SpinnerPadrao, 25, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SpinnerPadrao, 25, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SpinnerPadrao, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SpinnerPadrao, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_SpinnerPadrao, lv_color_hex(0x7B00FF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_SpinnerPadrao, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_SPINNERTITLE = lv_label_create(ui_SpinnerPadrao);
lv_obj_set_width( ui_SPINNERTITLE, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SPINNERTITLE, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SPINNERTITLE, 0 );
lv_obj_set_y( ui_SPINNERTITLE, 55 );
lv_obj_set_align( ui_SPINNERTITLE, LV_ALIGN_CENTER );
lv_label_set_text(ui_SPINNERTITLE,"Loading");
lv_obj_add_flag( ui_SPINNERTITLE, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_font(ui_SPINNERTITLE, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_StatusSalaLivre, ui_event_StatusSalaLivre, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_StatusSalaOcupada, ui_event_StatusSalaOcupada, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_StatusSalaReservada, ui_event_StatusSalaReservada, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_NomeSala, ui_event_NomeSala, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_EstenderDropdown, ui_event_EstenderDropdown, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_LiberarDropdown, ui_event_LiberarDropdown, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ReservarDropdown, ui_event_ReservarDropdown, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_RealizarCheckinDropDown, ui_event_RealizarCheckinDropDown, LV_EVENT_ALL, NULL);

}
