// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: wiserroommini

#include "ui.h"

void ui_SetupPage_screen_init(void)
{
ui_SetupPage = lv_obj_create(NULL);
lv_obj_clear_flag( ui_SetupPage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Roller1 = lv_roller_create(ui_SetupPage);
lv_roller_set_options( ui_Roller1, "RIO DE JANEIRO\nSAO PAULO\nRIBEIRAO PRETO\nUBATUBA\n", LV_ROLLER_MODE_NORMAL );
lv_obj_set_height( ui_Roller1, 87);
lv_obj_set_width( ui_Roller1, lv_pct(76));
lv_obj_set_x( ui_Roller1, 0 );
lv_obj_set_y( ui_Roller1, 80 );
lv_obj_set_align( ui_Roller1, LV_ALIGN_TOP_MID );
lv_obj_set_style_text_font(ui_Roller1, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(ui_Roller1, &lv_font_montserrat_22, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Roller1, lv_color_hex(0x7800FF), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Roller1, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_SetupPage);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_y( ui_Label2, 33 );
lv_obj_set_x( ui_Label2, lv_pct(-1) );
lv_obj_set_align( ui_Label2, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label2,"ESCOLHA A SALA:");
lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BOTAOCONFIRMARNOVASALA = lv_btn_create(ui_SetupPage);
lv_obj_set_width( ui_BOTAOCONFIRMARNOVASALA, 140);
lv_obj_set_height( ui_BOTAOCONFIRMARNOVASALA, 50);
lv_obj_set_x( ui_BOTAOCONFIRMARNOVASALA, 116 );
lv_obj_set_y( ui_BOTAOCONFIRMARNOVASALA, 80 );
lv_obj_set_align( ui_BOTAOCONFIRMARNOVASALA, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BOTAOCONFIRMARNOVASALA, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BOTAOCONFIRMARNOVASALA, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BOTAOCONFIRMARNOVASALA, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BOTAOCONFIRMARNOVASALA, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_BOTAOCONFIRMARNOVASALA, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_BOTAOCONFIRMARNOVASALA);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"CONFIRMAR");
lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BOTAOSAIRDAESCOLHADESALA = lv_btn_create(ui_SetupPage);
lv_obj_set_width( ui_BOTAOSAIRDAESCOLHADESALA, 140);
lv_obj_set_height( ui_BOTAOSAIRDAESCOLHADESALA, 50);
lv_obj_set_x( ui_BOTAOSAIRDAESCOLHADESALA, -108 );
lv_obj_set_y( ui_BOTAOSAIRDAESCOLHADESALA, 80 );
lv_obj_set_align( ui_BOTAOSAIRDAESCOLHADESALA, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BOTAOSAIRDAESCOLHADESALA, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BOTAOSAIRDAESCOLHADESALA, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BOTAOSAIRDAESCOLHADESALA, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BOTAOSAIRDAESCOLHADESALA, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_BOTAOSAIRDAESCOLHADESALA, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_BOTAOSAIRDAESCOLHADESALA);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"SAIR");
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Roller1, ui_event_Roller1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BOTAOCONFIRMARNOVASALA, ui_event_BOTAOCONFIRMARNOVASALA, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BOTAOSAIRDAESCOLHADESALA, ui_event_BOTAOSAIRDAESCOLHADESALA, LV_EVENT_ALL, NULL);

}
